_BASE_: "Base-DPP.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DPP:
    NUM_PROPOSALS: 100
    NUM_CLASSES: 80
    PRUNE_STAGE: 1,3,5
    PRUNE_WEIGHT: 10.0
    PRUNE_WEIGHT_ST: 10.0
    PRUNE_MARGIN: 0.0
    PRUNE_LOWERBOUND: 1.0
    PRUNE_MULTIPLIER: 2.0
    PRUNE_LOWERBOUND_ST: 1.0
    PRUNE_MULTIPLIER_ST: 1.0
    PRUNE_INTERIOU_WEIGHT: 1.0
    PRUNE_INTERIOU_ST_WEIGHT: 1.0
    PRUNE_INTERIOU_ALPHA: 1.0

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  BASE_LR: 0.0000025
  PRUNE_BRANCH_LR: 0.000025
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
